// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_main module generated by `tlgen.py` tool
// all reset signals should be generated from one reset signal to not make any deadlock
//
// Interconnect
// management_core_data
//   -> s1n_8
//     -> management_scratchpad_data
//     -> management_scratchpad_instr
//     -> vicuna0_scratchpad_data
//     -> vicuna0_scratchpad_instr
//     -> vicuna1_scratchpad_data
//     -> vicuna1_scratchpad_instr
//     -> uart

module xbar_main (
  input clk_main_i,
  input rst_main_ni,

  // Host interfaces
  input  tlul_pkg::tl_h2d_t tl_management_core_data_i,
  output tlul_pkg::tl_d2h_t tl_management_core_data_o,

  // Device interfaces
  output tlul_pkg::tl_h2d_t tl_management_scratchpad_instr_o,
  input  tlul_pkg::tl_d2h_t tl_management_scratchpad_instr_i,
  output tlul_pkg::tl_h2d_t tl_management_scratchpad_data_o,
  input  tlul_pkg::tl_d2h_t tl_management_scratchpad_data_i,
  output tlul_pkg::tl_h2d_t tl_uart_o,
  input  tlul_pkg::tl_d2h_t tl_uart_i,
  output tlul_pkg::tl_h2d_t tl_vicuna0_scratchpad_instr_o,
  input  tlul_pkg::tl_d2h_t tl_vicuna0_scratchpad_instr_i,
  output tlul_pkg::tl_h2d_t tl_vicuna0_scratchpad_data_o,
  input  tlul_pkg::tl_d2h_t tl_vicuna0_scratchpad_data_i,
  output tlul_pkg::tl_h2d_t tl_vicuna1_scratchpad_instr_o,
  input  tlul_pkg::tl_d2h_t tl_vicuna1_scratchpad_instr_i,
  output tlul_pkg::tl_h2d_t tl_vicuna1_scratchpad_data_o,
  input  tlul_pkg::tl_d2h_t tl_vicuna1_scratchpad_data_i,

  input prim_mubi_pkg::mubi4_t scanmode_i
);

  import tlul_pkg::*;
  import tl_main_pkg::*;

  // scanmode_i is currently not used, but provisioned for future use
  // this assignment prevents lint warnings
  logic unused_scanmode;
  assign unused_scanmode = ^scanmode_i;

  tl_h2d_t tl_s1n_8_us_h2d ;
  tl_d2h_t tl_s1n_8_us_d2h ;


  tl_h2d_t tl_s1n_8_ds_h2d [7];
  tl_d2h_t tl_s1n_8_ds_d2h [7];

  // Create steering signal
  logic [2:0] dev_sel_s1n_8;



  assign tl_management_scratchpad_data_o = tl_s1n_8_ds_h2d[0];
  assign tl_s1n_8_ds_d2h[0] = tl_management_scratchpad_data_i;

  assign tl_management_scratchpad_instr_o = tl_s1n_8_ds_h2d[1];
  assign tl_s1n_8_ds_d2h[1] = tl_management_scratchpad_instr_i;

  assign tl_vicuna0_scratchpad_data_o = tl_s1n_8_ds_h2d[2];
  assign tl_s1n_8_ds_d2h[2] = tl_vicuna0_scratchpad_data_i;

  assign tl_vicuna0_scratchpad_instr_o = tl_s1n_8_ds_h2d[3];
  assign tl_s1n_8_ds_d2h[3] = tl_vicuna0_scratchpad_instr_i;

  assign tl_vicuna1_scratchpad_data_o = tl_s1n_8_ds_h2d[4];
  assign tl_s1n_8_ds_d2h[4] = tl_vicuna1_scratchpad_data_i;

  assign tl_vicuna1_scratchpad_instr_o = tl_s1n_8_ds_h2d[5];
  assign tl_s1n_8_ds_d2h[5] = tl_vicuna1_scratchpad_instr_i;

  assign tl_uart_o = tl_s1n_8_ds_h2d[6];
  assign tl_s1n_8_ds_d2h[6] = tl_uart_i;

  assign tl_s1n_8_us_h2d = tl_management_core_data_i;
  assign tl_management_core_data_o = tl_s1n_8_us_d2h;

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_8 = 3'd7;
    if ((tl_s1n_8_us_h2d.a_address &
         ~(ADDR_MASK_MANAGEMENT_SCRATCHPAD_DATA)) == ADDR_SPACE_MANAGEMENT_SCRATCHPAD_DATA) begin
      dev_sel_s1n_8 = 3'd0;

    end else if ((tl_s1n_8_us_h2d.a_address &
                  ~(ADDR_MASK_MANAGEMENT_SCRATCHPAD_INSTR)) == ADDR_SPACE_MANAGEMENT_SCRATCHPAD_INSTR) begin
      dev_sel_s1n_8 = 3'd1;

    end else if ((tl_s1n_8_us_h2d.a_address &
                  ~(ADDR_MASK_VICUNA0_SCRATCHPAD_DATA)) == ADDR_SPACE_VICUNA0_SCRATCHPAD_DATA) begin
      dev_sel_s1n_8 = 3'd2;

    end else if ((tl_s1n_8_us_h2d.a_address &
                  ~(ADDR_MASK_VICUNA0_SCRATCHPAD_INSTR)) == ADDR_SPACE_VICUNA0_SCRATCHPAD_INSTR) begin
      dev_sel_s1n_8 = 3'd3;

    end else if ((tl_s1n_8_us_h2d.a_address &
                  ~(ADDR_MASK_VICUNA1_SCRATCHPAD_DATA)) == ADDR_SPACE_VICUNA1_SCRATCHPAD_DATA) begin
      dev_sel_s1n_8 = 3'd4;

    end else if ((tl_s1n_8_us_h2d.a_address &
                  ~(ADDR_MASK_VICUNA1_SCRATCHPAD_INSTR)) == ADDR_SPACE_VICUNA1_SCRATCHPAD_INSTR) begin
      dev_sel_s1n_8 = 3'd5;

    end else if ((tl_s1n_8_us_h2d.a_address &
                  ~(ADDR_MASK_UART)) == ADDR_SPACE_UART) begin
      dev_sel_s1n_8 = 3'd6;
end
  end


  // Instantiation phase
  tlul_socket_1n #(
    .HReqDepth (4'h0),
    .HRspDepth (4'h0),
    .DReqDepth (28'h0),
    .DRspDepth (28'h0),
    .N         (7)
  ) u_s1n_8 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_s1n_8_us_h2d),
    .tl_h_o       (tl_s1n_8_us_d2h),
    .tl_d_o       (tl_s1n_8_ds_h2d),
    .tl_d_i       (tl_s1n_8_ds_d2h),
    .dev_select_i (dev_sel_s1n_8)
  );

endmodule
