// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tb__xbar_connect generated by `tlgen.py` tool

xbar_main dut();

`DRIVE_CLK(clk_main_i)

initial force dut.clk_main_i = clk_main_i;

// TODO, all resets tie together
initial force dut.rst_main_ni = rst_n;

// Host TileLink interface connections
`CONNECT_TL_HOST_IF(management_core_instr, dut, clk_main_i, rst_n)
`CONNECT_TL_HOST_IF(management_core_data, dut, clk_main_i, rst_n)

// Device TileLink interface connections
`CONNECT_TL_DEVICE_IF(management_scratchpad_instr, dut, clk_main_i, rst_n)
`CONNECT_TL_DEVICE_IF(management_scratchpad_data, dut, clk_main_i, rst_n)
`CONNECT_TL_DEVICE_IF(uart, dut, clk_main_i, rst_n)
`CONNECT_TL_DEVICE_IF(vicuna0_scratchpad_instr, dut, clk_main_i, rst_n)
`CONNECT_TL_DEVICE_IF(vicuna0_scratchpad_data, dut, clk_main_i, rst_n)
`CONNECT_TL_DEVICE_IF(vicuna1_scratchpad_instr, dut, clk_main_i, rst_n)
`CONNECT_TL_DEVICE_IF(vicuna1_scratchpad_data, dut, clk_main_i, rst_n)
