// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_main_bind module generated by `tlgen.py` tool for assertions
module xbar_main_bind;
`ifndef GATE_LEVEL
  // Host interfaces
  bind xbar_main tlul_assert #(.EndpointType("Device")) tlul_assert_host_management_core_instr (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_management_core_instr_i),
    .d2h    (tl_management_core_instr_o)
  );
  bind xbar_main tlul_assert #(.EndpointType("Device")) tlul_assert_host_management_core_data (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_management_core_data_i),
    .d2h    (tl_management_core_data_o)
  );

  // Device interfaces
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_management_scratchpad_instr (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_management_scratchpad_instr_o),
    .d2h    (tl_management_scratchpad_instr_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_management_scratchpad_data (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_management_scratchpad_data_o),
    .d2h    (tl_management_scratchpad_data_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_uart (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_uart_o),
    .d2h    (tl_uart_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_vicuna0_scratchpad_instr (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_vicuna0_scratchpad_instr_o),
    .d2h    (tl_vicuna0_scratchpad_instr_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_vicuna0_scratchpad_data (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_vicuna0_scratchpad_data_o),
    .d2h    (tl_vicuna0_scratchpad_data_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_vicuna1_scratchpad_instr (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_vicuna1_scratchpad_instr_o),
    .d2h    (tl_vicuna1_scratchpad_instr_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_vicuna1_scratchpad_data (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_vicuna1_scratchpad_data_o),
    .d2h    (tl_vicuna1_scratchpad_data_i)
  );
`endif
endmodule
