// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_management_peripherals module generated by `tlgen.py` tool
// all reset signals should be generated from one reset signal to not make any deadlock
//
// Interconnect
// management_core_data
//   -> s1n_4
//     -> management_scratchpad_data
//     -> uart
//     -> dma_register_interface

module xbar_management_peripherals (
  input clk_main_i,
  input rst_main_ni,

  // Host interfaces
  input  tlul_pkg::tl_h2d_t tl_management_core_data_i,
  output tlul_pkg::tl_d2h_t tl_management_core_data_o,

  // Device interfaces
  output tlul_pkg::tl_h2d_t tl_management_scratchpad_data_o,
  input  tlul_pkg::tl_d2h_t tl_management_scratchpad_data_i,
  output tlul_pkg::tl_h2d_t tl_uart_o,
  input  tlul_pkg::tl_d2h_t tl_uart_i,
  output tlul_pkg::tl_h2d_t tl_dma_register_interface_o,
  input  tlul_pkg::tl_d2h_t tl_dma_register_interface_i,

  input prim_mubi_pkg::mubi4_t scanmode_i
);

  import tlul_pkg::*;
  import tl_management_peripherals_pkg::*;

  // scanmode_i is currently not used, but provisioned for future use
  // this assignment prevents lint warnings
  logic unused_scanmode;
  assign unused_scanmode = ^scanmode_i;

  tl_h2d_t tl_s1n_4_us_h2d ;
  tl_d2h_t tl_s1n_4_us_d2h ;


  tl_h2d_t tl_s1n_4_ds_h2d [3];
  tl_d2h_t tl_s1n_4_ds_d2h [3];

  // Create steering signal
  logic [1:0] dev_sel_s1n_4;



  assign tl_management_scratchpad_data_o = tl_s1n_4_ds_h2d[0];
  assign tl_s1n_4_ds_d2h[0] = tl_management_scratchpad_data_i;

  assign tl_uart_o = tl_s1n_4_ds_h2d[1];
  assign tl_s1n_4_ds_d2h[1] = tl_uart_i;

  assign tl_dma_register_interface_o = tl_s1n_4_ds_h2d[2];
  assign tl_s1n_4_ds_d2h[2] = tl_dma_register_interface_i;

  assign tl_s1n_4_us_h2d = tl_management_core_data_i;
  assign tl_management_core_data_o = tl_s1n_4_us_d2h;

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_4 = 2'd3;
    if ((tl_s1n_4_us_h2d.a_address &
         ~(ADDR_MASK_MANAGEMENT_SCRATCHPAD_DATA)) == ADDR_SPACE_MANAGEMENT_SCRATCHPAD_DATA) begin
      dev_sel_s1n_4 = 2'd0;

    end else if ((tl_s1n_4_us_h2d.a_address &
                  ~(ADDR_MASK_UART)) == ADDR_SPACE_UART) begin
      dev_sel_s1n_4 = 2'd1;

    end else if ((tl_s1n_4_us_h2d.a_address &
                  ~(ADDR_MASK_DMA_REGISTER_INTERFACE)) == ADDR_SPACE_DMA_REGISTER_INTERFACE) begin
      dev_sel_s1n_4 = 2'd2;
end
  end


  // Instantiation phase
  tlul_socket_1n #(
    .HReqDepth (4'h0),
    .HRspDepth (4'h0),
    .DReqDepth (12'h0),
    .DRspDepth (12'h0),
    .N         (3)
  ) u_s1n_4 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_s1n_4_us_h2d),
    .tl_h_o       (tl_s1n_4_us_d2h),
    .tl_d_o       (tl_s1n_4_ds_h2d),
    .tl_d_i       (tl_s1n_4_ds_d2h),
    .dev_select_i (dev_sel_s1n_4)
  );

endmodule
