// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `tlgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"management_scratchpad_data", '{
        '{32'h00100000, 32'h0010ffff}
    }},
    '{"uart", '{
        '{32'h80001000, 32'h80001fff}
    }},
    '{"dma_register_port", '{
        '{32'h90001000, 32'h90001fff}
}}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"management_core_data", 0, '{
        "management_scratchpad_data",
        "uart",
        "dma_register_port"}}
};
