// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `tlgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"management_scratchpad_instr", '{
        '{32'h00000000, 32'h0000ffff}
    }},
    '{"management_scratchpad_data", '{
        '{32'h00100000, 32'h0010ffff}
    }},
    '{"vicuna0_scratchpad_instr", '{
        '{32'h00200000, 32'h0020ffff}
    }},
    '{"vicuna0_scratchpad_data", '{
        '{32'h00300000, 32'h0030ffff}
    }},
    '{"vicuna1_scratchpad_instr", '{
        '{32'h00400000, 32'h0040ffff}
    }},
    '{"vicuna1_scratchpad_data", '{
        '{32'h00500000, 32'h0050ffff}
}}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"dma", 0, '{
        "management_scratchpad_data",
        "management_scratchpad_instr",
        "vicuna0_scratchpad_data",
        "vicuna0_scratchpad_instr",
        "vicuna1_scratchpad_data",
        "vicuna1_scratchpad_instr"}}
};
